CREATE DATABASE VENDAS;

USE VENDAS;

CREATE TABLE PRODUTOS(
    ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30),
    ESTOQUE_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DOUBLE
    );
   
 CREATE TABLE VENDA(
 
    ID_VENDA INT NOT  NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO_VENDA INT NOT NULL,
    ID_PRODUTO INT,
    QUANTIDADE INT
   
 );
 
 INSERT INTO PRODUTOS (DESCRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("CUZCUZ",35,4);
 INSERT INTO PRODUTOS (DESCRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("FEIJAO",45,5);
 INSERT INTO PRODUTOS (DESCRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("ARROZ",55,6); 
 INSERT INTO PRODUTOS (DESCRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("GELATINA",65,7);
 INSERT INTO PRODUTOS (DESCRICAO, ESTOQUE_PRODUTO, PRECO_PRODUTO) VALUE ("MACARRAO",75,8);
 
 DELIMITER $$
 
 CREATE TRIGGER ATUALIZAR_ESTOQUE AFTER INSERT
 ON VENDA 
 FOR EACH ROW
 
 BEGIN
 
 UPDATE PRODUTOS SET ESTOQUE_PRODUTO = ESTOQUE_PRODUTO-NEW.QUANTIDADE 
 WHERE ID_PRODUTO = NEW.ID_PRODUTO;
 
 END $$
 
 DELIMITER ;
 
 SELECT * FROM PRODUTOS;
 
 INSERT INTO VENDA(NUMERO_VENDA, ID_PRODUTO, QUANTIDADE) VALUES (10, 4, 10);